project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ".."
preserve_hierarchy: false
files:
  - source: loc_for_upload/Dalamud_Localizable.json
    translation: UIRes/loc/dalamud/dalamud_%two_letters_code%.json
