blank_issues_enabled: false
contact_links:
  - name: XIVLauncher Discord
    url: https://discord.gg/aSuNjps
    about: Discussion about XIVLauncher and it's development - Your question may be answered here!
