name: Update Dalamud localization files

on:
  workflow_dispatch:
  push:

jobs:
  export-loc-files:
    runs-on: windows-latest

    steps:
      - name: Checkout Dalamud master
        uses: actions/checkout@v4
        with:
          repository: goatcorp/Dalamud
          path: Dalamud
          submodules: recursive

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run LocExporter
        run: |
          cd Dalamud/tools/Dalamud.LocExporter
          dotnet run -c Release

      - name: Upload loc file artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Dalamud_Localizable'
          if-no-files-found: error
          path: 'Dalamud/tools/Dalamud.LocExporter/Dalamud_Localizable.json'
